# Controller generated by Typus, use it to extend admin functionality.
class Admin::AdsController < Admin::ResourcesController
  def approve
    if get_object.approve
      redirect_to :back, :notice => "审核通过。"
    else
      redirect_to :back, :notice => "不能审核已经通过审核的。"
    end
  end

  def reject
    if get_object.reject
      redirect_to :back, :notice => "审核不通过。"
    else
      redirect_to :back, :notice => "拒绝审核出错。"
    end
  end

  def theme
    @ads = Ad.paginate :all, :page => params[:page], :per_page => 30
  end

  def update_themes
    edited_ids = params[:ad_ids].try(:keys) ||[]
    non_themes_ids = params[:ids] - edited_ids

    if params[:ad_ids]
      params[:ad_ids].each do |ad_id, themes|
        Ad.update_all(["themes=?", themes.uniq.join(",")], ["id=?", ad_id])
      end

      flash[:notice] = "Update successfully。"
    end

    # clean cancelled themes
    Ad.update_all(["themes=?", ""], ["id in (?)", non_themes_ids])

    redirect_to :action => :theme, :page => params[:page]
  end
end
