# Controller generated by Typus, use it to extend admin functionality.
class Admin::AdsController < Admin::ResourcesController
  def approve
    if get_object.approve
      redirect_to :back, :notice => "审核通过。"
    else
      redirect_to :back, :notice => "不能审核已经通过审核的。"
    end
  end

  def reject
    if get_object.reject
      redirect_to :back, :notice => "审核不通过。"
    else
      redirect_to :back, :notice => "拒绝审核出错。"
    end
  end

  def theme
    @ads = Ad.paginate :all, :page => params[:page], :per_page => 20
  end

  def update_themes
    flash[:notice] = "Update successfully。"
    params[:ad_ids].each do |ad_id, themes|
      Ad.update_all(["themes=?", themes.uniq.join(",")], ["id=?", ad_id])
    end
    redirect_to :action => :theme, :page => params[:page]
  end
end
