# Controller generated by Typus, use it to extend admin functionality.
class Admin::CompaniesController < Admin::ResourcesController
  def theme
    @companies = Company.paginate :all, :page => params[:page], :per_page => 20
  end

  def update_themes
    flash[:notice] = "Update successfully。"
    params[:company_ids].each do |company_id, themes|
      Company.update_all(["themes=?", themes.uniq.join(",")], ["id=?", company_id])
    end
    redirect_to :action => :theme, :page => params[:page]
  end
end
