# Controller generated by Typus, use it to extend admin functionality.
class Admin::JobsController < Admin::ResourcesController
  def approve
    if get_object.approve
      redirect_to :back, :notice => "审核通过。"
    else
      redirect_to :back, :notice => "不能审核已经通过审核的工作。"
    end
  end
end