# Controller generated by Typus, use it to extend admin functionality.
class Admin::UsersController < Admin::ResourcesController
  def login
    if UserSession.create(get_object)
      redirect_to "/", :notice => "登录 “#{get_object.email}” 成功。"
    else
      redirect_to :back, :notice => "登录失败。"
    end
  end
end
