# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  Ad: create, read, update, delete
  Counter: create, read, update, delete
  Revenue: create, read, update, delete
  Service: create, read, update, delete
  ServiceItem: create, read, update, delete
  ServiceItemAmount: create, read, update, delete
  StarredResume: create, read, update, delete
  Subscription: create, read, update, delete
  TitledImage: create, read, update, delete
  Voucher: create, read, update, delete
