# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

AdPosition:
  fields:
    default: name, job_list_tags, width, height, type, style, partner_id
    form: name, job_list_tags, width, height, type, style, partner_id
  order_by:
  relationships:
  filters:
  search: name
  application: Partner

Adclick:
  fields:
    default: ad_position_id, remote_ip, source_page, dest_page, http_user_agent, remote_host, request_uri, ad_position
    form: remote_ip, source_page, dest_page, http_user_agent, remote_host, request_uri, ad_position
  order_by:
  relationships: ad_position
  filters:
  search:
  application: Partner

Certification:
  fields:
    default: resume_id, name, get_at, resume
    form: resume_id, name, get_at, resume
  order_by:
  relationships: image, resume
  filters:
  search: name
  application: Jobseeker

Company:
  fields:
    default: user_id, name, size, province, city, address, homepage, contact_name, phone_number, logo_file_name, user
    form: user_id, name, size, province, city, address, homepage, contact_name, phone_number, desc, logo_file_name, user
  order_by:
  relationships: job_applications, jobs, presentations, products, resumes, user
  filters:
  search: name
  application: Company

CoverLetter:
  fields:
    default: resume_id, name
    form: resume_id, name, content
  order_by:
  relationships:
  filters:
  search: name
  application: Jobseeker

Job:
  fields:
    default: name, location_province, location_city, category_humanize, salary_range, highlight_start_at, highlight_end_at, start_at, end_at, company
    form: name, location_province, location_city, category, vacancy, content, requirement, welfare, desc, salary_range, highlight_start_at, highlight_end_at, start_at, end_at, company_id, company
  order_by:
  relationships: company, job_applications, user
  filters:
  search: name
  application: Company

JobApplication:
  fields:
    default: job_id, resume_id, cover_letter_id, state, rating, resume, cover_letter, job
    form: job_id, resume_id, cover_letter_id, state, rating, resume, cover_letter, job
  order_by:
  relationships: company, cover_letter, job, resume
  filters:
  search:
  application: Jobseeker

Language:
  fields:
    default: resume_id, name, level, resume
    form: resume_id, name, level, resume
  order_by:
  relationships: resume
  filters:
  search: name
  application: Jobseeker

Partner:
  fields:
    default: user_id, name, url, contact_name, phone_number, site_size, user
    form: user_id, name, url, contact_name, phone_number, site_size, desc, user
  order_by:
  relationships: user
  filters:
  search: name
  application: Partner

Presentation:
  fields:
    default: type, parent_id, name, file_file_name
    form: type, parent_id, name, desc, file_file_name
  order_by:
  relationships:
  filters:
  search: name
  application: Company

PreviousJob:
  fields:
    default: resume_id, company_name, company_size, job_title, start_at, end_at, resume
    form: resume_id, company_name, company_size, job_title, start_at, end_at, resume
  order_by:
  relationships: resume
  filters:
  search:
  application: Jobseeker

Product:
  fields:
    default: type, parent_id, name, file_file_name
    form: type, parent_id, name, desc, file_file_name
  order_by:
  relationships:
  filters:
  search: name
  application: Company

Project:
  fields:
    default: type, parent_id, name, file_file_name
    form: type, parent_id, name, desc, file_file_name
  order_by:
  relationships:
  filters:
  search: name
  application: Jobseeker

Resume:
  fields:
    default: user_id, name, gender, working_years, degree, major, birthday, hometown_province, hometown_city, current_residence_province, current_residence_city, email, phone_number, expected_salary, expected_positions, expected_job_location, current_working_state, highlight_start_at, highlight_end_at, is_sending_sms, portrait_file_name, user
    form: user_id, name, gender, working_years, degree, major, birthday, hometown_province, hometown_city, current_residence_province, current_residence_city, email, phone_number, expected_salary, expected_job_location, current_working_state, highlight_start_at, highlight_end_at, is_sending_sms, portrait_file_name, user
  order_by:
  relationships: certifications, cover_letters, job_applications, jobs, languages, previous_jobs, projects, schools, skills, starred_jobs, user
  filters:
  search: name
  application: Jobseeker

School:
  fields:
    default: resume_id, name, major, start_at, end_at, resume
    form: resume_id, name, major, start_at, end_at, resume
  order_by:
  relationships: resume
  filters:
  search: name
  application: Jobseeker

Skill:
  fields:
    default: resume_id, name, level, resume
    form: resume_id, name, level, resume
  order_by:
  relationships: resume
  filters:
  search: name
  application: Jobseeker

StarredJob:
  fields:
    default: resume_id, job_id, rating, resume, job
    form: resume_id, job_id, rating, resume, job
  order_by:
  relationships: job, resume
  filters:
  search:
  application: Jobseeker

User:
  fields:
    default: email, login_count, failed_login_count, last_request_at, current_login_at, last_login_at, current_login_ip, last_login_ip
    form: email, login_count, failed_login_count, last_request_at, current_login_at, last_login_at, current_login_ip, last_login_ip
    cvs: email, login_count
  export: csv, xml
  order_by: last_request_at, current_login_at, last_login_at, current_login_ip, last_login_ip
  relationships: company, jobseeker, partner
  filters: last_request_at
  search: email
  application: Account

Ad:
  fields:
    default: position, name, company, display_type_humanize, state, start_at, end_at
    form: position, name, desc, display_type, url, state, start_at, end_at, company, image, province, city, period
    options:
      selectors: display_type, state
      templates:
        desc: text
  order_by: position
  relationships: company
  filters: display_type
  search: name, company
  application: Company

Counter:
  fields:
    default: click, happened_at, parent_id, type
    form: click, happened_at, parent_id, type
  order_by:
  relationships:
  filters:
  search:
  application: Partner

Revenue:
  fields:
    default: partner_id, period_start_at, period_end_at, state
    form: partner_id, period_start_at, period_end_at, state
  order_by:
  relationships:
  filters:
  search:
  application: Partner

StarredResume:
  fields:
    default: company_id, resume_id, rating, resume, company
    form: company_id, resume_id, rating, resume, company
  order_by:
  relationships: company, resume
  filters:
  search:
  application: Company

Subscription:
  fields:
    default: resume_id, keywords, last_sent_at
    form: resume_id, keywords, last_sent_at
  order_by:
  relationships:
  filters:
  search:
  application: Jobseeker

Service:
  fields:
    default: serving_target_type_humanize, name, price
    form: serving_target_type, name, desc, price
    options:
      selectors: serving_target_type
  order_by:
  relationships: service_item_amounts, service_items
  filters:
  search: name
  application: Service

ServiceItem:
  fields:
    default: name, service_length
    form: name, desc, service_length
  order_by:
  relationships: service, service_item_amounts
  filters:
  search: name
  application: Service

ServiceItemAmount:
  fields:
    default: amount, service, service_item
    form: amount, service, service_item
  order_by:
  relationships: service, service_item
  filters:
  search:
  application: Service

Voucher:
  fields:
    default: code, amount, state, user, service_item
    form: amount, state, user, service_item
    options:
      selectors: state
  order_by:
  relationships: service_item, user
  filters:
  search:
  application: Service