# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  User: create, read, update, delete, login, confirm
  Certification: create, read, update, delete
  Company: create, read, update, delete, theme, update_themes, change_email, add_to_featured_company, add_to_famous_company
  CoverLetter: create, read, update, delete
  Job: create, read, update, delete, approve, reject, theme, update_themes, recommend_resumes, upload_xml, import, add_to_urgent_ad, do_import
  JobApplication: create, read, update, delete
  Language: create, read, update, delete
  Partner: create, read, update, delete, approve, reject, send_commission, withdraw
  Presentation: create, read, update, delete
  PreviousJob: create, read, update, delete
  Product: create, read, update, delete
  Project: create, read, update, delete
  Resume: create, read, update, delete
  School: create, read, update, delete
  Skill: create, read, update, delete
  StarredJob: create, read, update, delete
  Ad: create, read, update, delete, approve, reject, theme, update_themes
  Counter: create, read, update, delete
  Service: create, read, update, delete
  ServiceItem: create, read, update, delete
  ServiceItemAmount: create, read, update, delete
  Subscription: create, read, update, delete
  Voucher: create, read, update, delete