development:
  log_mail: true
  user_class_name: "User"
  # user_locale_column: "locale"
  mount_at: "/admin/mail_engine"
  intercept_email: "hlxwell+itjob@gmail.com"
  default_from: "info@itjob.fm"
  access_check_method: "allow_to_access_mail_system"
  sendgrid:
    sendgrid_user: "a@theplant.jp"
    sendgrid_key: "plant^o^"
    sendgrid_category: "itjob.fm_dev"

test:
  log_mail: true
  user_class_name: "User"
  mount_at: "/admin/mail_engine"
  access_check_method: "allow_to_access_mail_system"
  sendgrid:
    sendgrid_user: "a@theplant.jp"
    sendgrid_key: "plant^o^"
    sendgrid_category: "itjob.fm_test"

production:
  log_mail: true
  user_class_name: "User"
  mount_at: "/admin/mail_engine"
  default_from: "info@itjob.fm"
  access_check_method: "allow_to_access_mail_system"
  sendgrid:
    sendgrid_user: "a@theplant.jp"
    sendgrid_key: "plant^o^"
    sendgrid_category: "itjob.fm_prod"